### ISSUE TITLE
arc-length error on calculation

### ISSUE THREAD

**Issue by moiseevigor** [moiseevigor/elliptic#17]
the bug in the code see pull request https://github.com/moiseevigor/elliptic/pull/16

**Comment by drbitboy** [comment]
Two more things:

1) We will need to update the two tests in the comments; I provide some samples in the changes I made.  Note also that arc lengths between [theta0,theta]  = [pi/3, pi/6 should be the same for any [a,b] pair of values, even if the value of [theta0, theta1] and/or [a,b] are reversed.

2) The first line of that file had

    cdfunction [arclength] = arclength_ellipse(a, b, theta0, theta1)

and it should have been

    function [arclength] = arclength_ellipse(a, b, theta0, theta1)

so I expect no one has been using it very much.

**Comment by moiseevigor** [comment]
Thank you Brian for following the question, the typo I've introduced recently https://github.com/moiseevigor/elliptic/commit/522b673f191c9011daefe76212e9d8d465fcc792 while actually responding to some questions about arc-length of ellipse. Unfortunately I cannot follow in detail all the theory right now so we'll proceed with merging.
